name: XrayInformer
version: 3.0.1_beta
description: This plugin helps to protect your server from Xrayers
author: bwinkl04
main: com.gmail.bwinkl04.XrayInformer.XrayInformer
depend: [LogBlock]
commands:
  xcheck:
    description: Xray check for a given player, enter /xcheck reload to reload the config
permissions: 
  xcheck.check:
    description: Allows the XrayInformer to check players
    default: false
  xcheck.receive:
    description: These members will receive messages when a cheater joins the game
    default: false