name: XrayInformer
version: 2.2.2
description: This plugin helps to protect your server from x-rayers
author: bwinkl04
main: com.gmail.bwinkl04.XrayInformer
depend: [LogBlock]
commands:
  xcheck:
    description: xRay check for a given player, enter /xcheck reload to reload the config
permissions: 
  xcheck.check:
    description: Allows the XrayInformer to check players
    default: false